before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pTidDiPWKYMQbMafnhr0a9btEsLH/BhegyGJaDQNeFmDf08cKEnKpRctvkJkm1S/+3LwLbXr03EZaOyqM8fg2K+7ooyTG0I0Z9tX4qIAVKvFkDBiE+3n42F4DFpTVRXBefCYtLsDY3g7Hg3eiS9R7m+lkVtsX7e/QelpD/Ad7vGLlajG5z/AeZh0FK3xM2N9039n5zQo7vsOJOIxsIYh8Yi52UWW+7K0nUHpwfHhmwivy65AhP+lrRhCJXge/E0oPOg5vfrc7iAMfi8xRKHZNYrT5+XZWT7/vEioY/hHBkDQUeSJFkkomwkGq14ReOTu/sJ9MqRz+PVcqiwP+gFn/AnYNIIfAKlWzp9ZkPYlcdtngFC15RZaPm/XRWmDxoms/osK9q9Nz5aDas7iKCMyJ4eIRyKU+ZknclKmdDF0u7cRxRNiomClcJm4bi6qOf9MkbvfmeuhXKmMuXhjmXyndRityr7JSq/0uOpHSU0haY2GEX4PyI6h23DDE7ZCxYTuDaqa8MKUlQXDoXVbxgqjTVqCU0dmSR/2by63eRgtC9L9skWnFS7uP5cfi/EY1qB/STtjbcrE1cIpADEA1QVNC+xhAjm66wcXWatM0E+xTAleNA16LDjvBVBzQVIk+MEncia/0KvRAVkGlH4pcL8Pth8tXc+g+x6rQBf+LETnxiM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
